name 'puppet-dhcp'
version '1.1.1'
source 'https://github.com/buzzdeee/buzzdeee-dhcpd.git'
author 'buzzdeee'
license 'Apache License Version 2.0'
summary 'Manage the OpenBSD dhcpd daemon'
description 'A Puppet module to manage the OpenBSD dhcpd server.'
project_page 'https://github.com/buzzdeee/buzzdeee-dhcpd'

dependency 'puppetlabs/concat', '>= 1.1.0'
