name 'puppet-dhcp'
version '1.1.1'
source 'https://github.com/xaque208/puppet-dhcp.git'
author 'zleslie'
license 'Apache License Version 2.0'
summary 'Manage the ISC DHCP Daemon'
description 'A Puppet module to deploy and manage the ISC DHCP server.'
project_page 'https://github.com/xaque208/puppet-dhcp'

dependency 'puppetlabs/concat', '>= 1.1.0'
